realIpHeader: X-Forwarded-For
spring:
  datasource:
    druid:
      url: jdbc:mysql://host.docker.internal:3306/permission?useSSL=false&serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=true&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
    host: host.docker.internal
    port: 6379

graphql:
  tools:
    introspection-enabled: false