spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/permission?useSSL=false&serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useLegacyDatetimeCode=true&allowPublicKeyRetrieval=true
      username: root
      password: "Root;123HeHa"
  profiles:
    active: dev
logging:
  file:
    name: application.log
server:
  port: 8088